//! Build script: parse the vendored, verbatim `ucum-essence.xml` and emit a
//! generated Rust source file (`$OUT_DIR/ucum_tables.rs`) containing the prefix
//! and atom tables.
//!
//! Parsing happens here, at build time, so that no XML/serialization dependency
//! leaks into the runtime dependency tree of the published crate. The essence
//! file is redistributed verbatim under the UCUM Copyright Notice and License
//! (see `vendor/UCUM-LICENSE.md`); this script only *reads* it.

use std::env;
use std::fs;
use std::path::Path;

include!("src/build_support.rs");

fn main() {
    println!("cargo:rerun-if-changed=vendor/ucum-essence.xml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/build_support.rs");

    let xml = fs::read_to_string("vendor/ucum-essence.xml")
        .expect("vendor/ucum-essence.xml must be present");

    let (prefixes, atoms) = generate_tables(&xml).expect("failed to parse ucum-essence.xml");

    let out = format!(
        "// @generated by build.rs from vendor/ucum-essence.xml. Do not edit.\n\
         pub static PREFIXES: &[PrefixDef] = &[\n{prefixes}];\n\n\
         pub static ATOMS: &[AtomDef] = &[\n{atoms}];\n"
    );

    let dest = Path::new(&env::var("OUT_DIR").unwrap()).join("ucum_tables.rs");
    fs::write(dest, out).expect("write generated tables");
}
